### ISSUE TITLE
Panic when calling State::new()

### ISSUE THREAD

**Issue by KJ4TIP** [QCGPU/qcgpu-rust#4] opened 2018-07-30 08:20 UTC
I attempted to compile and run a short example program using qcgpu-rust and received the following panic when creating a new state.  I don't have any experience using OpenCL, so I'm unsure whether my particular OpenCL configuration is causing this or not.

    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Kernel argument type mismatch. The argument named: 'target' at index: [1] should be a 'uint' (ArgType { base_type: Uint, cardinality: One, is_ptr: false }).', libcore/result.rs:945:5                                                                                                
    stack backtrace:
       0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
                 at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
       1: std::sys_common::backtrace::print
                 at libstd/sys_common/backtrace.rs:71
                 at libstd/sys_common/backtrace.rs:59
       2: std::panicking::default_hook::{{closure}}
                 at libstd/panicking.rs:211
       3: std::panicking::default_hook
                 at libstd/panicking.rs:227
       4: std::panicking::rust_panic_with_hook
                 at libstd/panicking.rs:475
       5: std::panicking::continue_panic_fmt
                 at libstd/panicking.rs:390
       6: rust_begin_unwind
                 at libstd/panicking.rs:325
       7: core::panicking::panic_fmt
                 at libcore/panicking.rs:77
       8: core::result::unwrap_failed
                 at /checkout/src/libcore/macros.rs:26
       9: <core::result::Result<T, E>>::unwrap
                 at /checkout/src/libcore/result.rs:782
      10: qcgpu::state::State::new
                 at /home/******/.cargo/registry/src/github.com-1ecc6299db9ec823/qcgpu-0.1.0/src/state.rs:60
      11: qcgpu_test::main
                 at src/main.rs:5
      12: std::rt::lang_start::{{closure}}
                 at /checkout/src/libstd/rt.rs:74
      13: std::panicking::try::do_call
                 at libstd/rt.rs:59
                 at libstd/panicking.rs:310
      14: __rust_maybe_catch_panic
                 at libpanic_unwind/lib.rs:106
      15: std::rt::lang_start_internal
                 at libstd/panicking.rs:289
                 at libstd/panic.rs:392
                 at libstd/rt.rs:58
      16: std::rt::lang_start
                 at /checkout/src/libstd/rt.rs:74
      17: main
      18: __libc_start_main
      19: _start

For reference, the sample program:

    extern crate qcgpu;
    use qcgpu::State;
    
    fn main() {
        let mut state = State::new(2,0);
        state.x(0);
    
        println!("Measured: {}", state.measure());
    }

And here's the output of `clinfo`:

    Number of platforms                               1
      Platform Name                                   AMD Accelerated Parallel Processing
      Platform Vendor                                 Advanced Micro Devices, Inc.
      Platform Version                                OpenCL 2.0 AMD-APP (1800.11)
      Platform Profile                                FULL_PROFILE
      Platform Extensions                             cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
      Platform Extensions function suffix             AMD
    
      Platform Name                                   AMD Accelerated Parallel Processing
    Number of devices                                 1
      Device Name                                     Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
      Device Vendor                                   GenuineIntel
      Device Vendor ID                                0x1002
      Device Version                                  OpenCL 1.2 AMD-APP (1800.11)
      Driver Version                                  1800.11 (sse2,avx)
      Device OpenCL C Version                         OpenCL C 1.2 
      Device Type                                     CPU
      Device Board Name (AMD)                         
      Device Topology (AMD)                           (n/a)
      Device Profile                                  FULL_PROFILE
      Device Available                                Yes
      Compiler Available                              Yes
      Linker Available                                Yes
      Max compute units                               4
      Max clock frequency                             1403MHz
      Device Partition                                (core, cl_ext_device_fission)
        Max number of sub-devices                     4
        Supported partition types                     equally, by counts, by affinity domain
        Supported affinity domains                    L3 cache, L2 cache, L1 cache, next partitionable
        Supported partition types (ext)               equally, by counts, by affinity domain
        Supported affinity domains (ext)              L3 cache, L2 cache, L1 cache, next fissionable
      Max work item dimensions                        3
      Max work item sizes                             1024x1024x1024
      Max work group size                             1024
      Preferred work group size multiple              1
      Preferred / native vector sizes                 
        char                                                16 / 16      
        short                                                8 / 8       
        int                                                  4 / 4       
        long                                                 2 / 2       
        half                                                 4 / 4        (n/a)
        float                                                8 / 8       
        double                                               4 / 4        (cl_khr_fp64)
      Half-precision Floating-point support           (n/a)
      Single-precision Floating-point support         (core)
        Denormals                                     Yes
        Infinity and NANs                             Yes
        Round to nearest                              Yes
        Round to zero                                 Yes
        Round to infinity                             Yes
        IEEE754-2008 fused multiply-add               Yes
        Support is emulated in software               No
        Correctly-rounded divide and sqrt operations  Yes
      Double-precision Floating-point support         (cl_khr_fp64)
        Denormals                                     Yes
        Infinity and NANs                             Yes
        Round to nearest                              Yes
        Round to zero                                 Yes
        Round to infinity                             Yes
        IEEE754-2008 fused multiply-add               Yes
        Support is emulated in software               No
      Address bits                                    64, Little-Endian
      Global memory size                              16776560640 (15.62GiB)
      Error Correction support                        No
      Max memory allocation                           4194140160 (3.906GiB)
      Unified memory for Host and Device              Yes
      Minimum alignment for any data type             128 bytes
      Alignment of base address                       1024 bits (128 bytes)
      Global Memory cache type                        Read/Write
      Global Memory cache size                        32768 (32KiB)
      Global Memory cache line size                   64 bytes
      Image support                                   Yes
        Max number of samplers per kernel             16
        Max size for 1D images from buffer            65536 pixels
        Max 1D or 2D image array size                 2048 images
        Max 2D image size                             8192x8192 pixels
        Max 3D image size                             2048x2048x2048 pixels
        Max number of read image args                 128
        Max number of write image args                64
      Local memory type                               Global
      Local memory size                               32768 (32KiB)
      Max number of constant args                     8
      Max constant buffer size                        65536 (64KiB)
      Max size of kernel argument                     4096 (4KiB)
      Queue properties                                
        Out-of-order execution                        No
        Profiling                                     Yes
      Prefer user sync for interop                    Yes
      Profiling timer resolution                      1ns
      Profiling timer offset since Epoch (AMD)        1530994088516357846ns (Sat Jul  7 15:08:08 2018)
      Execution capabilities                          
        Run OpenCL kernels                            Yes
        Run native kernels                            Yes
        SPIR versions                                 1.2
      printf() buffer size                            65536 (64KiB)
      Built-in kernels                                
      Device Extensions                               cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_spir cl_khr_gl_event 

    NULL platform behavior
      clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  AMD Accelerated Parallel Processing
      clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [AMD]
      clCreateContext(NULL, ...) [default]            Success [AMD]
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No devices found in platform
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  Success (1)
        Platform Name                                 AMD Accelerated Parallel Processing
        Device Name                                   Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
        Platform Name                                 AMD Accelerated Parallel Processing
        Device Name                                   Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
    
    ICD loader properties
      ICD loader Name                                 OpenCL ICD Loader
      ICD loader Vendor                               OCL Icd free software
      ICD loader Version                              2.2.12
      ICD loader Profile                              OpenCL 2.2

**Comment by adamisntdead** [comment] 2018-07-30 10:02
Hey, just checking that you are using `qcgpu-rust = 0.1` in your `cargo.lock`?

**Comment by KJ4TIP** [comment] 2018-07-30 17:56
I'm using `qcgpu = "0.1"`

**Comment by adamisntdead** [comment] 2018-07-30 20:12
Hm, this is weird - I reran the tests, all passing:

https://travis-ci.org/QCGPU/qcgpu-rust

I will have a look at this over the next few days

**Comment by adamisntdead** [comment] 2018-08-14 11:07
Closing as I couldn't reproduce the error

**Closed** 2018-08-14 11:07 UTC
Labels: bug, question
